redirects:

# Basics

  ../basics/authentication: ./api/basics/authentication/README.md
  basics/authentication/client-credential-token: ./api/basics/authentication/client-credential-token.md
  basics/authentication/implicit-token: ./api/basics/authentication/implicit-token.md
  basics/authentication/permissions: ./api/basics/authentication/permissions.md
  basics/content-type: ./api/basics/content-type.md
  basics/errors: ./api/basics/errors.md
  basics/includes: ./api/basics/includes.md
  basics/pagination: ./api/basics/pagination.md
  basics/links: ./api/basics/links.md
  basics/filtering: ./api/basics/filtering/README.md
  basics/filtering/equals: ./api/basics/filtering/equals.md
  basics/filtering/like: ./api/basics/filtering/like.md
  basics/filtering/chaining: ./api/basics/filtering/chaining.md
  basics/sorting: ./api/basics/sorting.md
  basics/safe-characters: ./api/basics/safe-characters.md
  basics/moltin-api-changelog: ./api/basics/moltin-api-changelog.md

## Catalog

  catalog/products: ./api/catalog/products/README.md
  catalog/products/get-all-products: ./api/catalog/products/get-all-products.md
  catalog/products/get-a-product: ./api/catalog/products/get-a-product.md
  catalog/products/create-a-product: ./api/catalog/products/create-a-product.md
  catalog/products/update-a-product: ./api/catalog/products/update-a-product.md
  catalog/products/delete-a-product: ./api/catalog/products/delete-a-product.md
  catalog/products/filtering: ./api/catalog/products/filtering.md
  catalog/products/relationships: ./api/catalog/products/relationships/README.md
  catalog/products/relationships/brand-relationship: ./api/catalog/products/relationships/brand-relationship.md
  catalog/products/relationships/category-relationship: ./api/catalog/products/relationships/category-relationship.md
  catalog/products/relationships/collection-relationships: ./api/catalog/products/relationships/collection-relationships.md
  catalog/products/relationships/file-relationships: ./api/catalog/products/relationships/file-relationships.md
  catalog/products/relationships/main-image-relationship: ./api/catalog/products/relationships/main-image-relationship.md
  catalog/products/relationships/variations-relationship: ./api/catalog/products/relationships/variations-relationship.md
  catalog/product-variations: ./api/catalog/product-variations/README.md
  catalog/product-variations/get-all-product-variations: ./api/catalog/product-variations/get-all-product-variations.md
  catalog/product-variations/get-product-variations: ./api/catalog/product-variations/get-product-variations.md
  catalog/product-variations/create-a-product-variation: ./api/catalog/product-variations/create-a-product-variation.md
  catalog/product-variations/update-a-product-variation: ./api/catalog/product-variations/update-a-product-variation.md
  catalog/product-variations/delete-a-product-variation: ./api/catalog/product-variations/delete-a-product-variation.md
  catalog/product-variations/build-child-products: ./api/catalog/product-variations/build-child-products.md
  catalog/product-variations/options: ./api/catalog/product-variations/options/README.md
  catalog/product-variations/options/get-a-product-variation-option: ./api/catalog/product-variations/options/get-a-product-variation-option.md
  catalog/product-variations/options/get-all-product-variation-options: ./api/catalog/product-variations/options/get-all-product-variation-options.md
  catalog/product-variations/options/create-product-variation-option: ./api/catalog/product-variations/options/create-product-variation-option.md
  catalog/product-variations/options/update-product-variation-option: ./api/catalog/product-variations/options/update-product-variation-option.md
  catalog/product-variations/options/delete-product-variation-option: ./api/catalog/product-variations/options/delete-product-variation-option.md
  catalog/product-variations/modifiers: ./api/catalog/product-variations/modifiers/README.md
  catalog/product-variations/modifiers/get-all-product-modifiers: ./api/catalog/product-variations/modifiers/get-all-product-modifiers.md
  catalog/product-variations/modifiers/get-a-product-modifier: ./api/catalog/product-variations/modifiers/get-a-product-modifier.md
  catalog/product-variations/modifiers/create-product-modifier: ./api/catalog/product-variations/modifiers/create-product-modifier.md
  catalog/product-variations/modifiers/update-product-modifier: ./api/catalog/product-variations/modifiers/update-product-modifier.md
  catalog/product-variations/modifiers/delete-product-modifier: ./api/catalog/product-variations/modifiers/delete-product-modifier.md
  catalog/brands: ./api/catalog/brands/README.md
  catalog/brands/get-all-brands: ./api/catalog/brands/get-all-brands.md
  catalog/brands/get-a-brand: ./api/catalog/brands/get-a-brand.md
  catalog/brands/create-a-brand: ./api/catalog/brands/create-a-brand.md
  catalog/brands/update-a-brand: ./api/catalog/brands/update-a-brand.md
  catalog/brands/delete-a-brand: ./api/catalog/brands/delete-a-brand.md
  catalog/brands/filtering: ./api/catalog/brands/filtering.md
  catalog/brands/relationships: ./api/catalog/brands/relationships/README.md
  catalog/brands/relationships/brand-relationships: ./api/catalog/brands/relationships/brand-relationships.md
  catalog/brands/relationships/parent-relationships: ./api/catalog/brands/relationships/parent-relationships.md
  catalog/brands/relationships/child-relationships: ./api/catalog/brands/relationships/child-relationships.md
  catalog/categories: ./api/catalog/categories/README.md
  catalog/categories/get-all-categories: ./api/catalog/categories/get-all-categories.md
  catalog/categories/get-a-category: ./api/catalog/categories/get-a-category.md
  catalog/categories/create-a-category: ./api/catalog/categories/create-a-category.md
  catalog/categories/update-a-category: ./api/catalog/categories/update-a-category.md
  catalog/categories/delete-a-category: ./api/catalog/categories/delete-a-category.md
  catalog/categories/filtering: ./api/catalog/categories/filtering.md
  catalog/categories/relationships: ./api/catalog/categories/relationships/README.md
  catalog/categories/relationships/category-relationships: ./api/catalog/categories/relationships/category-relationships.md
  catalog/categories/relationships/parent-relationships: ./api/catalog/categories/relationships/parent-relationships.md
  catalog/categories/relationships/child-relationships: ./api/catalog/categories/relationships/child-relationships.md
  catalog/collections: ./api/catalog/collections/README.md
  catalog/collections/get-all-collections: ./api/catalog/collections/get-all-collections.md
  catalog/collections/get-a-collection: ./api/catalog/collections/get-a-collection.md
  catalog/collections/create-a-collection: ./api/catalog/collections/create-a-collection.md
  catalog/collections/update-a-collection: ./api/catalog/collections/update-a-collection.md
  catalog/collections/delete-a-collection: ./api/catalog/collections/delete-a-collection.md
  catalog/collections/filtering: ./api/catalog/collections/filtering.md
  catalog/collections/relationships: ./api/catalog/collections/relationships/README.md
  catalog/collections/relationships/collection-relationships: ./api/catalog/collections/relationships/collection-relationships.md
  catalog/collections/relationships/parent-relationships: ./api/catalog/collections/relationships/parent-relationships.md
  catalog/collections/relationships/child-relationships: ./api/catalog/collections/relationships/child-relationships.md
  catalog/inventory: ./api/catalog/inventory/README.md
  catalog/inventory/get-all-inventory: ./api/catalog/inventory/get-all-inventory.md
  catalog/inventory/get-all-product-stock: ./api/catalog/inventory/get-all-product-stock.md
  catalog/inventory/stock-transactions: ./api/catalog/inventory/stock-transactions.md
  catalog/inventory/update-inventory: ./api/catalog/inventory/update-inventory.md

## Carts & Checkout

  carts-and-checkout/carts: ./api/carts-and-checkout/carts/README.md
  carts-and-checkout/carts/get-a-cart: ./api/carts-and-checkout/carts/get-a-cart.md
  carts-and-checkout/carts/add-product-to-cart: ./api/carts-and-checkout/carts/add-product-to-cart.md
  carts-and-checkout/carts/add-custom-item-to-cart: ./api/carts-and-checkout/carts/add-custom-item-to-cart.md
  carts-and-checkout/carts/add-promotion-to-cart: ./api/carts-and-checkout/carts/add-promotion-to-cart.md
  carts-and-checkout/carts/delete-a-cart: ./api/carts-and-checkout/carts/delete-a-cart.md
  carts-and-checkout/carts/cart-items: ./api/carts-and-checkout/carts/cart-items/README.md
  carts-and-checkout/carts/cart-items/get-cart-items: ./api/carts-and-checkout/carts/cart-items/get-cart-items.md
  carts-and-checkout/carts/cart-items/update-cart-item: ./api/carts-and-checkout/carts/cart-items/update-cart-item.md
  carts-and-checkout/carts/cart-items/remove-cart-item: ./api/carts-and-checkout/carts/cart-items/remove-cart-item.md
  carts-and-checkout/carts/cart-items/tax-items: ./api/carts-and-checkout/carts/cart-items/tax-items/README.md
  carts-and-checkout/carts/cart-items/tax-items/create-a-tax-item: ./api/carts-and-checkout/carts/cart-items/tax-items/create-a-tax-item.md
  carts-and-checkout/carts/cart-items/tax-items/delete-a-tax-item: ./api/carts-and-checkout/carts/cart-items/tax-items/delete-a-tax-item.md
  carts-and-checkout/checkout: ./api/carts-and-checkout/checkout.md
  carts-and-checkout/promotions: ./api/carts-and-checkout/promotions/README.md
  carts-and-checkout/promotions/create-promotion: ./api/carts-and-checkout/promotions/create-promotion.md
  carts-and-checkout/promotions/get-promotions: ./api/carts-and-checkout/promotions/get-promotions.md
  carts-and-checkout/promotions/get-a-promotion: ./api/carts-and-checkout/promotions/get-a-promotion.md
  carts-and-checkout/promotions/update-promotions: ./api/carts-and-checkout/promotions/update-promotions.md
  carts-and-checkout/promotions/get-promotion-codes: ./api/carts-and-checkout/promotions/get-promotion-codes.md
  carts-and-checkout/promotions/create-promotion-codes: ./api/carts-and-checkout/promotions/create-promotion-codes.md
  carts-and-checkout/promotions/delete-promotion-codes: ./api/carts-and-checkout/promotions/delete-promotion-codes.md

## Payments

  payments/gateways: ./api/payments/gateways/README.md
  payments/gateways/get-all-gateways: ./api/payments/gateways/get-all-gateways.md
  payments/gateways/get-a-gateway: ./api/payments/gateways/get-a-gateway.md
  payments/gateways/update-gateway-settings: ./api/payments/gateways/update-gateway-settings.md
  payments/gateways/configure-adyen: ./api/payments/gateways/configure-adyen.md
  payments/gateways/configure-braintree: ./api/payments/gateways/configure-braintree.md
  payments/gateways/configure-stripe: ./api/payments/gateways/configure-stripe.md
  payments/gateways/configure-cardconnect: ./api/payments/gateways/configure-cardconnect.md
  payments/paying-for-an-order: ./api/payments/paying-for-an-order/README.md
  payments/paying-for-an-order/manual-payments: ./api/payments/paying-for-an-order/manual-payments.md
  payments/paying-for-an-order/stripe-payments: ./api/payments/paying-for-an-order/stripe-payments.md
  payments/paying-for-an-order/cardconnect-payments: ./api/payments/paying-for-an-order/cardconnect-payments.md
  payments/paying-for-an-order/adyen-payments: ./api/payments/paying-for-an-order/adyen-payments.md
  payments/paying-for-an-order/braintree-payments: ./api/payments/paying-for-an-order/braintree-payments.md
  payments/transactions: ./api/payments/transactions.md

## Orders & Customers

  orders-and-customers/orders: ./api/orders-and-customers/orders/README.md
  orders-and-customers/orders/get-all-orders: ./api/orders-and-customers/orders/get-all-orders.md
  orders-and-customers/orders/get-an-order: ./api/orders-and-customers/orders/get-an-order.md
  orders-and-customers/orders/update-an-order: ./api/orders-and-customers/orders/update-an-order.md
  orders-and-customers/orders/order-items: ./api/orders-and-customers/orders/order-items.md
  orders-and-customers/orders/filtering: ./api/orders-and-customers/orders/filtering.md
  orders-and-customers/orders/exporting: ./api/orders-and-customers/orders/exporting.md
  orders-and-customers/customers: ./api/orders-and-customers/customers/README.md
  orders-and-customers/customers/get-all-customers: ./api/orders-and-customers/customers/get-all-customers.md
  orders-and-customers/customers/get-a-customer: ./api/orders-and-customers/customers/get-a-customer.md
  orders-and-customers/customers/create-a-customer: ./api/orders-and-customers/customers/create-a-customer.md
  orders-and-customers/customers/update-a-customer: ./api/orders-and-customers/customers/update-a-customer.md
  orders-and-customers/customers/delete-a-customer: ./api/orders-and-customers/customers/delete-a-customer.md
  orders-and-customers/customers/filtering: ./api/orders-and-customers/customers/filtering.md
  orders-and-customers/customers/customer-tokens: ./api/orders-and-customers/customers/customer-tokens.md
  orders-and-customers/addresses: ./api/orders-and-customers/addresses/README.md
  orders-and-customers/addresses/get-all-addresses: ./api/orders-and-customers/addresses/get-all-addresses.md
  orders-and-customers/addresses/get-an-address: ./api/orders-and-customers/addresses/get-an-address.md
  orders-and-customers/addresses/create-an-address: ./api/orders-and-customers/addresses/create-an-address.md
  orders-and-customers/addresses/update-an-address: ./api/orders-and-customers/addresses/update-an-address.md
  orders-and-customers/addresses/delete-an-address: ./api/orders-and-customers/addresses/delete-an-address.md

## Advanced

  advanced/events: ./api/advanced/events/README.md
  advanced/events/observable-events: ./api/advanced/events/observable-events.md
  advanced/events/event-payload: ./api/advanced/events/event-payload.md
  advanced/events/get-all-events: ./api/advanced/events/get-all-events.md
  advanced/events/get-an-event: ./api/advanced/events/get-an-event.md
  advanced/events/create-an-event: ./api/advanced/events/create-an-event.md
  advanced/events/update-an-event: ./api/advanced/events/update-an-event.md
  advanced/events/delete-an-event: ./api/advanced/events/delete-an-event.md
  advanced/events/logs: ./api/advanced/events/logs.md
  advanced/custom-data: ./api/advanced/custom-data/README.md
  advanced/custom-data/flows: ./api/advanced/custom-data/flows.md
  advanced/custom-data/fields: ./api/advanced/custom-data/fields.md
  advanced/custom-data/entries: ./api/advanced/custom-data/entries.md
  advanced/custom-data/entry-relationships: ./api/advanced/custom-data/entry-relationships.md
  advanced/custom-data/flow-field-validation-rules: ./api/advanced/custom-data/flow-field-validation-rules.md
  advanced/files: ./api/advanced/files/README.md
  advanced/files/get-all-files: ./api/advanced/files/get-all-files.md
  advanced/files/get-a-file: ./api/advanced/files/get-a-file.md
  advanced/files/create-a-file: ./api/advanced/files/create-a-file.md
  advanced/files/delete-a-file: ./api/advanced/files/delete-a-file.md
  advanced/files/filtering: ./api/advanced/files/filtering.md
  advanced/jobs: ./api/advanced/jobs/README.md
  advanced/jobs/get-all-jobs: ./api/advanced/jobs/get-all-jobs.md
  advanced/jobs/get-a-job: ./api/advanced/jobs/get-a-job.md
  advanced/jobs/create-a-job: ./api/advanced/jobs/create-a-job.md
  advanced/currencies: ./api/advanced/currencies/README.md
  advanced/currencies/get-all-currencies: ./api/advanced/currencies/get-all-currencies.md
  advanced/currencies/get-a-currency: ./api/advanced/currencies/get-a-currency.md
  advanced/currencies/create-a-currency: ./api/advanced/currencies/create-a-currency.md
  advanced/currencies/update-a-currency: ./api/advanced/currencies/update-a-currency.md
  advanced/currencies/delete-a-currency: ./api/advanced/currencies/delete-a-currency.md
  advanced/languages: ./api/advanced/languages.md
  advanced/settings: ./api/advanced/settings/README.md
  advanced/settings/get-all-settings: ./api/advanced/settings/get-all-settings.md
  advanced/settings/update-settings: ./api/advanced/settings/update-settings.md
  advanced/settings/supported-languages: ./api/advanced/settings/supported-languages.md
